name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15.6
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.6' 

    - name: Check out code
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.33.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Builder instance name
      run: echo ${{ steps.buildx.outputs.name }}

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    
    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --tag rpi-ws281x-builder \
          --load \
          --file ./docker/builder/Dockerfile .

    - name: Build examples
      run: |
        docker run --rm --env GO111MODULE=on \
          -v "$(pwd)"/examples/swiss:/go/src/swiss \
          -w /go/src/swiss \
          rpi-ws281x-builder \
          go build -o swiss -v .

        docker run --rm -v "$(pwd)"/examples/color_wipe:/go/src/color_wipe rpi-ws281x-builder go build -o src/color_wipe/color_wipe -v color_wipe
        docker run --rm -v "$(pwd)"/examples/hw:/go/src/hw rpi-ws281x-builder go build -o src/hw/hw -v hw
        docker run --rm -v "$(pwd)"/examples/invader8x8:/go/src/invader8x8 rpi-ws281x-builder go build -o src/invader8x8/invader8x8 -v invader8x8

    - name: Upload examples
      uses: actions/upload-artifact@v1
      with:
        name: examples
        path: |      
          examples/swiss/swiss
          examples/color_wipe/color_wipe
          examples/hw/hw
          examples/invader8x8/invader8x8
